baseURL = 'https://kpddd.github.io'
languageCode = 'en-us'
hasCJKLanguage = true
title = 'kpddd'
theme = 'LoveIt'

copyright = "kpddd"

# whether to use robots.txt
enableRobotsTXT = true
# whether to use git commit log
enableGitInfo = true
# whether to use emoji code
enableEmoji = true

[author]
name = "kpddd"
email = "kp9ddd@gmail.com"
link = "https://kpddd.github.io"

[params.utterances]
enable = true
repo = "kpddd/kpddd.github.io"
issueTerm = "pathname"
theme = "preferred-color-scheme"
crossorigin = "anonymous"